/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MyEventsRouteImport } from './routes/my-events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HostSetupRouteImport } from './routes/host-setup'
import { Route as HostSettingsRouteImport } from './routes/host-settings'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as HostsIdRouteImport } from './routes/hosts.$id'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as EventsIdEditRouteImport } from './routes/events_.$id.edit'
import { Route as EventsIdCheckinRouteImport } from './routes/events_.$id.checkin'

const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MyEventsRoute = MyEventsRouteImport.update({
  id: '/my-events',
  path: '/my-events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSetupRoute = HostSetupRouteImport.update({
  id: '/host-setup',
  path: '/host-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const HostSettingsRoute = HostSettingsRouteImport.update({
  id: '/host-settings',
  path: '/host-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsIdRoute = HostsIdRouteImport.update({
  id: '/hosts/$id',
  path: '/hosts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/events/new',
  path: '/events/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdEditRoute = EventsIdEditRouteImport.update({
  id: '/events_/$id/edit',
  path: '/events/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdCheckinRoute = EventsIdCheckinRouteImport.update({
  id: '/events_/$id/checkin',
  path: '/events/$id/checkin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/host-settings': typeof HostSettingsRoute
  '/host-setup': typeof HostSetupRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/register': typeof RegisterRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/events/$id/edit': typeof EventsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/host-settings': typeof HostSettingsRoute
  '/host-setup': typeof HostSetupRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/register': typeof RegisterRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/events/$id/checkin': typeof EventsIdCheckinRoute
  '/events/$id/edit': typeof EventsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/explore': typeof ExploreRoute
  '/host-settings': typeof HostSettingsRoute
  '/host-setup': typeof HostSetupRoute
  '/login': typeof LoginRoute
  '/my-events': typeof MyEventsRoute
  '/register': typeof RegisterRoute
  '/tickets': typeof TicketsRoute
  '/events/$id': typeof EventsIdRoute
  '/events/new': typeof EventsNewRoute
  '/hosts/$id': typeof HostsIdRoute
  '/invite/$token': typeof InviteTokenRoute
  '/events_/$id/checkin': typeof EventsIdCheckinRoute
  '/events_/$id/edit': typeof EventsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/explore'
    | '/host-settings'
    | '/host-setup'
    | '/login'
    | '/my-events'
    | '/register'
    | '/tickets'
    | '/events/$id'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events/$id/checkin'
    | '/events/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/explore'
    | '/host-settings'
    | '/host-setup'
    | '/login'
    | '/my-events'
    | '/register'
    | '/tickets'
    | '/events/$id'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events/$id/checkin'
    | '/events/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/explore'
    | '/host-settings'
    | '/host-setup'
    | '/login'
    | '/my-events'
    | '/register'
    | '/tickets'
    | '/events/$id'
    | '/events/new'
    | '/hosts/$id'
    | '/invite/$token'
    | '/events_/$id/checkin'
    | '/events_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  ExploreRoute: typeof ExploreRoute
  HostSettingsRoute: typeof HostSettingsRoute
  HostSetupRoute: typeof HostSetupRoute
  LoginRoute: typeof LoginRoute
  MyEventsRoute: typeof MyEventsRoute
  RegisterRoute: typeof RegisterRoute
  TicketsRoute: typeof TicketsRoute
  EventsIdRoute: typeof EventsIdRoute
  EventsNewRoute: typeof EventsNewRoute
  HostsIdRoute: typeof HostsIdRoute
  InviteTokenRoute: typeof InviteTokenRoute
  EventsIdCheckinRoute: typeof EventsIdCheckinRoute
  EventsIdEditRoute: typeof EventsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-events': {
      id: '/my-events'
      path: '/my-events'
      fullPath: '/my-events'
      preLoaderRoute: typeof MyEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-setup': {
      id: '/host-setup'
      path: '/host-setup'
      fullPath: '/host-setup'
      preLoaderRoute: typeof HostSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/host-settings': {
      id: '/host-settings'
      path: '/host-settings'
      fullPath: '/host-settings'
      preLoaderRoute: typeof HostSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/$id': {
      id: '/hosts/$id'
      path: '/hosts/$id'
      fullPath: '/hosts/$id'
      preLoaderRoute: typeof HostsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new': {
      id: '/events/new'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id/edit': {
      id: '/events_/$id/edit'
      path: '/events/$id/edit'
      fullPath: '/events/$id/edit'
      preLoaderRoute: typeof EventsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$id/checkin': {
      id: '/events_/$id/checkin'
      path: '/events/$id/checkin'
      fullPath: '/events/$id/checkin'
      preLoaderRoute: typeof EventsIdCheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  ExploreRoute: ExploreRoute,
  HostSettingsRoute: HostSettingsRoute,
  HostSetupRoute: HostSetupRoute,
  LoginRoute: LoginRoute,
  MyEventsRoute: MyEventsRoute,
  RegisterRoute: RegisterRoute,
  TicketsRoute: TicketsRoute,
  EventsIdRoute: EventsIdRoute,
  EventsNewRoute: EventsNewRoute,
  HostsIdRoute: HostsIdRoute,
  InviteTokenRoute: InviteTokenRoute,
  EventsIdCheckinRoute: EventsIdCheckinRoute,
  EventsIdEditRoute: EventsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
